### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: invalid ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=providers/5.0.9)

### ISSUE THREAD

**Issue by keoneokeoneo** [ikhvost/truffle-nest-box#3]
Hi. I tried to run your truffle box, but i failed and some error was shown. 
After `unbox', i ran ganache-cli and truffle migrate instructions.
But when i start node server, error was shown.

[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [NestFactory] Starting Nest application...
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] AppModule dependencies initialized +13ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] ConnectionModule dependencies initialized +0ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] ConfigModule dependencies initialized +0ms
ERROR: Cannot find Contract - undefined
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [InstanceLoader] MetacoinModule dependencies initialized +3ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [RoutesResolver] MetacoinController {/metacoin}: +13ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [RouterExplorer] Mapped {/metacoin/balance/:address, GET} route +1ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [RouterExplorer] Mapped {/metacoin/send-coin, POST} route +1ms
[Nest] 51594   - 2021. 05. 22. 오후 3:28:02   [NestApplication] Nest application successfully started +1ms
(node:51594) UnhandledPromiseRejectionWarning: Error: invalid ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=providers/5.0.9)
    at Logger.makeError (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at JsonRpcProvider.<anonymous> (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/providers/lib/base-provider.js:1561:36)
    at step (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/providers/lib/base-provider.js:46:23)
    at Object.next (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/providers/lib/base-provider.js:27:53)
    at fulfilled (/Users/keonhokim/Documents/work/truffle/truffle-nest-box/node_modules/@ethersproject/providers/lib/base-provider.js:18:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can i get some advice?

**Comment by demostenes1509** [comment]
Any news about this ?

**Comment by demostenes1509** [comment]
Can you provide a valid ENS name to work locally ? Im a little bit lost here ...

**Comment by mateuszperlak** [comment]
I have exactly the same issue with ENS running locally

**Comment by rewddd** [comment]
Piece of... Please fix it

**Comment by makewithabhishek** [comment]
Same issue here. Pls help!

**Comment by ikhvost** [comment]
To solve this problem, you need to create a file `.env` in the root directory and pass to `METACOIN_ADDRESS` variable address of created smart-contract from the blockchain network.

I created `.env.template` for the sample and updated the installation instructions in README.md.
